name: trading_journal
description: A native Android trading journal app using Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.65.0
  intl: ^0.18.1
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  excel: ^3.1.2
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
